#!/usr/bin/env bash
#BOOOOOOOOOOOOOOOOO
Start=1
End=100
while [ $Start -le $End ]; do
	if ((Start % 3==0)) && ((Start % 5==0)); then
		echo "FizzBuzz"
	elif ((Start % 3==0)); then
		echo "Fizz"
	elif ((Start % 5==0)); then
		echo "Buzz"
	else
		echo $Start
	fi
	((Start=Start+1))
done
