#!/usr/bin/env bash
#Myeyeshurt
if [ -e /etc/passwd ]; then
	while IFS=: read -r username uid home; do
		echo "$username"
		echo "$uid"
		echo "$home"
		echo
	done < /etc/passwd
else
	echo "The /etc/passwd file does not exist"
fi
